[[redirects]]
    from = "/*"
    to = "https://green.tymyrddin.eu/:splat"
    status = 301
    force = true

[build]
    publish = "build/html"
    command = "pip install sphinx && make html"
    image = "noble"
